"""init schema

Revision ID: 6e2668dce523
Revises: 
Create Date: 2026-05-13 11:56:30.472523

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e2668dce523'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sport_type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.REAL(), nullable=True),
    sa.Column('elevation_gain_meters', sa.REAL(), nullable=True),
    sa.Column('avg_hr', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr', sa.SmallInteger(), nullable=True),
    sa.Column('avg_power', sa.SmallInteger(), nullable=True),
    sa.Column('normalized_power', sa.SmallInteger(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_cadence', sa.SmallInteger(), nullable=True),
    sa.Column('training_load', sa.REAL(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_activities_source_source_id')
    )
    op.create_table('body_measurements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.REAL(), nullable=True),
    sa.Column('body_fat_pct', sa.REAL(), nullable=True),
    sa.Column('muscle_mass_kg', sa.REAL(), nullable=True),
    sa.Column('bone_mass_kg', sa.REAL(), nullable=True),
    sa.Column('water_pct', sa.REAL(), nullable=True),
    sa.Column('visceral_fat', sa.REAL(), nullable=True),
    sa.Column('bmi', sa.REAL(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_summary',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.SmallInteger(), nullable=True),
    sa.Column('hrv_ms', sa.REAL(), nullable=True),
    sa.Column('stress_avg', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_high', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_low', sa.SmallInteger(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', name='uq_daily_summary_date_source')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('records_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_of', 'version', name='uq_weekly_plans_week_of_version')
    )
    op.create_table('manual_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('rpe', sa.SmallInteger(), nullable=True),
    sa.Column('pain_score', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.create_index(
        "ix_activities_start_time_desc",
        "activities",
        [sa.text("start_time DESC")],
    )
    op.create_index(
        "ix_activities_sport_type_start_time_desc",
        "activities",
        ["sport_type", sa.text("start_time DESC")],
    )
    op.create_index(
        "ix_activities_source_start_time_desc",
        "activities",
        ["source", sa.text("start_time DESC")],
    )
    op.create_index(
        "ix_body_measurements_measured_at_desc",
        "body_measurements",
        [sa.text("measured_at DESC")],
    )
    op.create_index(
        "ix_daily_summary_date_desc",
        "daily_summary",
        [sa.text("date DESC")],
    )
    op.create_index(
        "ix_manual_logs_logged_at_desc",
        "manual_logs",
        [sa.text("logged_at DESC")],
    )
    op.create_index(
        "ix_manual_logs_activity_id",
        "manual_logs",
        ["activity_id"],
    )
    op.create_index(
        "ix_weekly_plans_week_of_desc",
        "weekly_plans",
        [sa.text("week_of DESC")],
    )
    op.create_index(
        "ix_ingestion_runs_source_started_at_desc",
        "ingestion_runs",
        ["source", sa.text("started_at DESC")],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_ingestion_runs_source_started_at_desc", table_name="ingestion_runs")
    op.drop_index("ix_weekly_plans_week_of_desc", table_name="weekly_plans")
    op.drop_index("ix_manual_logs_activity_id", table_name="manual_logs")
    op.drop_index("ix_manual_logs_logged_at_desc", table_name="manual_logs")
    op.drop_index("ix_daily_summary_date_desc", table_name="daily_summary")
    op.drop_index("ix_body_measurements_measured_at_desc", table_name="body_measurements")
    op.drop_index("ix_activities_source_start_time_desc", table_name="activities")
    op.drop_index("ix_activities_sport_type_start_time_desc", table_name="activities")
    op.drop_index("ix_activities_start_time_desc", table_name="activities")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_logs')
    op.drop_table('weekly_plans')
    op.drop_table('ingestion_runs')
    op.drop_table('daily_summary')
    op.drop_table('body_measurements')
    op.drop_table('activities')
    # ### end Alembic commands ###
